environment:
  python: "3.9"
build:
  commands:
    - pip install -r requirements.txt
    - apt-get update && apt-get install -y ffmpeg
    - pip install -r requirements.txt
start:
  command: python src/main.py
  env:
    FFMPEG_PATH: "/usr/bin/ffmpeg"  # Update this with the actual path to ffmpeg on Render